version: 2
updates:
  - package-ecosystem: "pub" # See documentation for possible values
    directory: "/" # Location of package manifests
    reviewers:
      - 'Itstor'
    schedule:
      interval: "weekly"
    commit-message:
      prefix: 'chore(deps): '
