include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_function_literals_in_foreach_calls: false
    prefer_single_quotes: true
    always_use_package_imports: true
    use_is_even_rather_than_modulo: true
    use_if_null_to_convert_nulls_to_bools: true
    use_raw_strings: true
    unnecessary_raw_strings: true
    unnecessary_parenthesis: true
    unnecessary_overrides: true
    unnecessary_lambdas: true
    use_decorated_box: true
    use_colored_box: true
    sort_child_properties_last: true
    unnecessary_await_in_return: true
    sized_box_for_whitespace: true
    prefer_foreach: true
    avoid_unnecessary_containers: true
    avoid_bool_literals_in_conditional_expressions: true
    use_key_in_widget_constructors: true
